# Generated by Django 3.1.1 on 2020-09-23 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200923_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='horarios',
            field=models.ManyToManyField(related_name='horarios', to='core.Horario'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='core.medico'),
        ),
    ]
