# Generated by Django 3.1.1 on 2020-09-24 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200923_2149'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agenda',
            unique_together={('dia', 'medico')},
        ),
    ]
